---
keycloak_internal_url: "{{ lookup('env', 'KEYCLOAK_INTERNAL_URL') }}"
keycloak_realm: "{{ lookup('env', 'KEYCLOAK_REALM') | default('sso', true) }}"
aap_controller_url: "{{ lookup('env', 'AAP_CONTROLLER_URL') }}"
aap_gateway_internal_url: "{{ lookup('env', 'AAP_GATEWAY_INTERNAL_URL') | default('http://aap.aap.svc:80', true) }}"
keycloak_external_url: "{{ lookup('env', 'KEYCLOAK_EXTERNAL_URL') }}"
