apiVersion: hybridsovereign.redhat/v1alpha1
kind: HybridFabric
metadata:
  name: lab-fabric
  namespace: sovereign-cloud
spec:
  enabled: true
  domainAsn: 65000
  underlay:
    nadName: fabric-underlay
    cidr: 192.168.64.0/18
    mtu: 1400
  borderGateway:
    loopback: 10.255.10.10
  vniPool:
    start: 50000
    end: 50511
  transportDefaults:
    mtu: 1442
    defaultTunnelType: none
