apiVersion: hybridsovereign.redhat/v1alpha1
kind: NetworkPlacement
metadata:
  name: payments-aws-prod
  namespace: entity-acme-corp
spec:
  network: payments-vpc
  backend:
    kind: CloudAWS
    name: aws-prod
  prefixes:
    - 10.50.0.0/24
