---
- version: 1
  group: hybridsovereign.redhat
  kind: QuayConfig
  role: kind_reconcile
  snakeCaseParameters: false
  finalizer:
    name: quayconfig.hybridsovereign.redhat/finalizer
    role: kind_reconcile
