---
- version: v1alpha1
  group: hybridsovereign.redhat
  kind: RbacConfig
  role: kind_reconcile
  snakeCaseParameters: false
  reconcilePeriod: 1h
  finalizer:
    name: rbacconfig.hybridsovereign.redhat/finalizer
    role: kind_reconcile
