---
- version: v1alpha1
  group: hybridsovereign.redhat
  kind: QuayConfig
  role: kind_reconcile
  snakeCaseParameters: false
  watchAnnotationsChanges: true
  reconcilePeriod: 120s
  finalizer:
    name: quayconfig.hybridsovereign.redhat/finalizer
    role: kind_reconcile
