---
- version: v1alpha1
  group: hybridsovereign.redhat
  kind: AAPConfig
  role: kind_reconcile
  snakeCaseParameters: false
  reconcilePeriod: 1h
  finalizer:
    name: aapconfig.hybridsovereign.redhat/finalizer
    role: kind_reconcile
