apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hybridsovereign-ansible-operator
  namespace: sovereign-cloud
  labels:
    app.kubernetes.io/part-of: hybridsovereign-gitops
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gitea-local
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sovereign-cloud-dashboard
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tenancy-dashboard
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sovereign-admin-plugin
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sovereign-tenant-plugin
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ansible-runner
  namespace: sovereign-cloud
  labels:
    hybridsovereign.redhat/gitops-owned: "true"
spec:
  lookupPolicy:
    local: true
