---
cloudoso_operator_namespace: sovereign-cloud
central_api_server: ""
central_sa_secret_name: osohelper-creator-sa
central_sa_secret_namespace: sovereign-cloud
eda_central_work_namespace: sovereign-cloud-jobs

clouds_yaml_path: "/tmp/eda-cloudoso-clouds.yaml"
clouds_yaml_cloud: "openstack"

default_external_network: "internet"
default_project_domain: "shc_domain"
default_region_name: "ATUIN"
openstack_admin_user: "shc_admin"

vault_init_secret_name: "vault-init-secrets"
vault_init_secret_namespace: "central-vault"
vault_init_addr: "http://vault-active.central-vault.svc:8200"

eda_dashboard_host: ""
