---
cloudoso_operator_namespace: sovereign-cloud
central_api_server: ""
central_sa_secret_name: osohelper-creator-sa
central_sa_secret_namespace: sovereign-cloud
eda_central_work_namespace: sovereign-cloud-jobs

clouds_yaml_path: "/tmp/eda-cloudoso-clouds.yaml"
clouds_yaml_cloud: "openstack"

default_external_network: "internet"
default_project_domain: "shc_domain"
default_region_name: "ATUIN"
openstack_admin_user: "shc_admin"

vault_init_secret_name: "vault-init"
vault_init_secret_namespace: "vault"
vault_init_addr: "{{ lookup('env', 'VAULT_ADDR') | default('http://vault.vault.svc:8200', true) }}"
vault_kv_mount: hybridsovereign
vault_root_token_key: rootToken


eda_dashboard_host: ""
