apiVersion: v2
name: hybridsovereign-primary-operator
description: Primary operator — Entity + plugin config CRDs on services cluster
type: application
version: 0.1.23
appVersion: "1.0.0"
keywords:
  - openshift
  - operator
  - entity
  - hybridsovereign
maintainers:
  - name: hybrid-sovereign-cloud
