---
assignment_operator_namespace: sovereign-cloud
acm_central_sa_secret_name: assignment-acm-creator-sa
acm_policy_namespace: sovereign-cloud-helpers
central_api_server: "{{ (lookup('env', 'CENTRAL_API_SERVER') | trim) or '' }}"
oci_registry_host: "{{ (lookup('env', 'OCI_HOST') | trim) or 'quay.signal9.gg' }}"
sovereign_assignment_chart_version: "0.2.3"
assignment_acm_policy_name: ""
assignment_provisioned: false

eda_dashboard_host: ""
