{{- if and (ne .Values.provider.type "Agent") (.Values.installConfigVault) -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-install-config
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName | default "vault-backend" }}
  target:
    name: {{ .Values.cluster.name }}-install-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: install-config.yaml
      remoteRef:
        key: {{ .Values.installConfigVault }}
        property: install-config.yaml
{{- end -}}
