---
# EDA decision environments — images from {{ lookup('env', 'OCI_HOST') }}/hybrid-sovereign
eda_decision_environments:
  - name: de-entity
    description: Hybrid Sovereign decision environment for entity
    image_url: "{{ quay_registry }}/de-entity:0.1.7"
    credential: quay-registry-credential
    organization: Default
  - name: de-team
    description: Hybrid Sovereign decision environment for team
    image_url: "{{ quay_registry }}/de-team:0.1.2"
    credential: quay-registry-credential
    organization: Default
  - name: de-assignment
    description: Hybrid Sovereign decision environment for assignment
    image_url: "{{ quay_registry }}/de-assignment:0.1.5"
    credential: quay-registry-credential
    organization: Default
  - name: de-project
    description: Hybrid Sovereign decision environment for project
    image_url: "{{ quay_registry }}/de-project:0.1.0"
    credential: quay-registry-credential
    organization: Default
  - name: de-platformopenshift
    description: Hybrid Sovereign decision environment for platformopenshift
    image_url: "{{ quay_registry }}/de-platformopenshift:0.1.5"
    credential: quay-registry-credential
    organization: Default
  - name: de-cloudoso
    description: Hybrid Sovereign decision environment for cloudoso
    image_url: "{{ quay_registry }}/de-cloudoso:0.1.8"
    credential: quay-registry-credential
    organization: Default
  - name: de-openstack-migration
    description: Hybrid Sovereign decision environment for openstack-migration
    image_url: "{{ quay_registry }}/de-openstack-migration:0.1.0"
    credential: quay-registry-credential
    organization: Default
  - name: de-cloudaws
    description: Hybrid Sovereign decision environment for cloudaws
    image_url: "{{ quay_registry }}/de-cloudaws:0.1.4"
    credential: quay-registry-credential
    organization: Default
  - name: de-persona
    description: Hybrid Sovereign decision environment for persona
    image_url: "{{ quay_registry }}/de-persona:0.1.2"
    credential: quay-registry-credential
    organization: Default
  - name: de-plugin-rbac
    description: Hybrid Sovereign decision environment for plugin-rbac
    image_url: "{{ quay_registry }}/de-plugin-rbac:0.1.3"
    credential: quay-registry-credential
    organization: Default
  - name: de-plugin-vault
    description: Hybrid Sovereign decision environment for plugin-vault
    image_url: "{{ quay_registry }}/de-plugin-vault:0.1.2"
    credential: quay-registry-credential
    organization: Default
  - name: de-plugin-aap
    description: Hybrid Sovereign decision environment for plugin-aap
    image_url: "{{ quay_registry }}/de-plugin-aap:0.1.3"
    credential: quay-registry-credential
    organization: Default
  - name: de-plugin-quay
    description: Hybrid Sovereign decision environment for plugin-quay
    image_url: "{{ quay_registry }}/de-plugin-quay:0.1.2"
    credential: quay-registry-credential
    organization: Default
