---
plugin_vault_operator_namespace: sovereign-cloud-plugins
plugin_vault_keycloak_internal_url: "{{ lookup('env', 'KEYCLOAK_INTERNAL_URL') | default('http://rhbk-services-service.rhbk.svc:8080', true) }}"
plugin_vault_keycloak_realm: "{{ lookup('env', 'KEYCLOAK_REALM') | default('sso', true) }}"
plugin_vault_keycloak_admin_secret: "{{ lookup('env', 'KEYCLOAK_ADMIN_SECRET') | default('rhbk-services-admin', true) }}"
plugin_vault_image: "{{ lookup('env', 'VAULT_IMAGE') }}"
