---
plugin_rbac_operator_namespace: sovereign-cloud-plugins
plugin_rbac_keycloak_realm: sso
plugin_rbac_keycloak_url_default: ""
eda_dashboard_host: "https://sovereign-aap-aap.apps.shc-cental5.lab.signal9.gg"
