{{- range .Values.projects }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.entity }}-{{ . }}
  labels:
    team: {{ printf "%s-%s" $.Values.entity $.Values.team | quote }}
    hybridsovereign.redhat/entity: {{ $.Values.entity | quote }}
    hybridsovereign.redhat/team: {{ $.Values.team | quote }}
    hybridsovereign.redhat/assignment-project: {{ . | quote }}
{{- end }}
