{{- if ne .Values.toolRbac.assignmentViewerGroup "" }}
{{- $devopsNs := printf "%s-%s-devops" .Values.entity .Values.team }}
{{- $istioNs := printf "%s-%s-istio" .Values.entity .Values.team }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assignment-viewer
  namespace: {{ $devopsNs }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.toolRbac.assignmentViewerGroup }}
{{- range .Values.projects }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assignment-viewer
  namespace: {{ $.Values.entity }}-{{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ $.Values.toolRbac.assignmentViewerGroup }}
{{- end }}
{{- if $.Values.features.istio }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assignment-viewer
  namespace: {{ $istioNs }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.toolRbac.assignmentViewerGroup }}
{{- end }}
{{- end }}
