---
platformopenshift_operator_namespace: sovereign-cloud
central_api_server: "https://api.central.{{ lookup('env', 'LAB_DOMAIN') }}:6443"
central_sa_secret_name: awshelper-creator-sa
oso_central_sa_secret_name: osohelper-creator-sa
central_sa_secret_namespace: sovereign-cloud
keycloak_internal_url: "{{ lookup('env', 'KEYCLOAK_INTERNAL_URL') | default('http://rhbk-services-service.rhbk.svc:8080', true) }}"
keycloak_external_url: "{{ lookup('env', 'KEYCLOAK_EXTERNAL_URL') }}"
keycloak_realm: "{{ lookup('env', 'KEYCLOAK_REALM') | default('sso', true) }}"
keycloak_admin_secret_name: "rhbk-admin-credentials"
